name: Auto Update README

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.md' # 只要任何 md 文件变动就触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 🔥 v3 升级为 v4 消除警告
      - name: Set up Python
        uses: actions/setup-python@v5 # 🔥 v4 升级为 v5 消除警告
        with:
          python-version: '3.x'
      - name: Run Update Script
        run: python update_readme.py
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: 自动更新阅读索引" && git push)